src/Entity/Burger.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BurgerRepository")
 */
class Burger
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2)
     */
    private $supp_double;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSuppDouble(): ?string
    {
        return $this->supp_double;
    }

    public function setSuppDouble(string $supp_double): self
    {
        $this->supp_double = $supp_double;

        return $this;
    }
}

src/Entity/User.php
<?php
/**
 * Created by PhpStorm.
 * User: Benoit
 * Date: 20/11/2019
 * Time: 12:41
 */

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }
}

src/Form/BurgerType.php
<?php

namespace App\Form;

use App\Entity\Burger;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BurgerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('price')
            ->add('supp_double')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Burger::class,
        ]);
    }
}

src/Controller/BurgerController.php
<?php

namespace App\Controller;

use App\Entity\Burger;
use App\Form\BurgerType;
use App\Repository\BurgerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/burger")
 */
class BurgerController extends AbstractController
{
    /**
     * @Route("/", name="burger_index", methods={"GET"})
     * @return Response
     */
    public function index(): Response
    {
        return $this->render('burger/index.html.twig');
    }

    /**
     * @Route("/list", name="burger_list", methods={"GET"})
     * @param BurgerRepository $burgerRepository
     * @param Request $request
     * @return Response
     */
    public function list(BurgerRepository $burgerRepository, Request $request): Response
    {
        $burgers = $burgerRepository->findAll();

        // Construction du JSON attendu par le Datatable
        $json_output = array(
            'draw' => $request->get('draw', 0), // Il faut conserver la valeur du paramètre "draw" reçu dans REQUEST
            'recordsTotal' => count($burgers),
            'recordsFiltered' => count($burgers),
            'data' => array()
        );

        foreach ($burgers as $burger) {

            $link_edit = $this->generateUrl('burger_edit', ['id' => $burger->getId()]);
            $link_show = $this->generateUrl('burger_show', ['id' => $burger->getId()]);

            $aRow = array(
                'id' => $burger->getId(),
                'name' => $burger->getName(),
                'desc' => $burger->getDescription(),
                'price' => $burger->getPrice(),
                'supp_double' => $burger->getSuppDouble(),
                'actions' => "<a href='{$link_edit}'>Modifier</a> | <a href='{$link_show}'>Détails</a>"
            );
            $json_output['data'][] = $aRow;
        }

        return new JsonResponse($json_output);
    }

    /**
     * @Route("/new", name="burger_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $burger = new Burger();
        $form = $this->createForm(BurgerType::class, $burger);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($burger);
            $entityManager->flush();

            return $this->redirectToRoute('burger_index');
        }

        return $this->render('burger/new.html.twig', [
            'burger' => $burger,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="burger_show", methods={"GET"})
     * @param Burger $burger
     * @return Response
     */
    public function show(Burger $burger): Response
    {
        return $this->render('burger/show.html.twig', [
            'burger' => $burger,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="burger_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Burger $burger
     * @return Response
     */
    public function edit(Request $request, Burger $burger): Response
    {
        $form = $this->createForm(BurgerType::class, $burger);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('burger_index');
        }

        return $this->render('burger/edit.html.twig', [
            'burger' => $burger,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="burger_delete", methods={"DELETE"})
     * @param Request $request
     * @param Burger $burger
     * @return Response
     */
    public function delete(Request $request, Burger $burger): Response
    {
        if ($this->isCsrfTokenValid('delete'.$burger->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($burger);
            $entityManager->flush();
        }

        return $this->redirectToRoute('burger_index');
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="default_index", methods={"GET"})
     * @return RedirectResponse
     */
    public function index(): Response
    {
        return $this->redirectToRoute('fos_user_security_login');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Gestion des Burgers{% endblock %}</title>
        {% block stylesheets %}
            <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}

        {% block javascripts %}
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        {% endblock %}
    </body>
</html>

templates/burger/_delete_form.html.twig
<form method="post" action="{{ path('burger_delete', {'id': burger.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ burger.id) }}">
    <button class="btn btn-danger"><i class="fa fa-trash"></i> Supprimer</button>
</form>

templates/burger/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success col-12"><i class="fa fa-save"></i> Sauvegarder</button>
{{ form_end(form) }}

templates/burger/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'un burger{% endblock %}

{% block body %}
    <div class="col-12">
        <h3>
            Modification d'un burger
            <a href="{{ path('burger_index') }}" class="btn btn-primary float-right mt-2"><i class="fa fa-step-backward"></i>Revenir à la liste</a>
        </h3>

        {{ include('burger/_form.html.twig', {'button_label': 'Update'}) }}

        <br/>

        {{ include('burger/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/burger/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des burgers{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="col-12">
        <h3>Liste des burgers</h3>

        <table id="burger_list" class="table">
            <thead>
                <tr>
                    <th class="thD" data-name="id">Id</th>
                    <th class="thD" data-name="name">Nom</th>
                    <th class="thD" data-name="desc">Description</th>
                    <th class="thD" data-name="price">Prix</th>
                    <th class="thD" data-name="supp_double">Supp double</th>
                    <th class="thD" data-name="actions">Actions</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>

        <a href="{{ path('burger_new') }}" class="btn btn-success"><i class="fa fa-plus"></i> Créer un burger</a>
    </div>
{% endblock %}

{% block javascripts %}

    {{ parent() }}
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

    <script>
        $(document).ready(function () {


            var arr = [];
            $('.thD').each(function() {

                if (typeof $(this).attr('data-name') !== 'undefined'){
                    arr.push( {'data':$(this).attr('data-name')});
                } else {
                    arr.push({'data':null});
                }

            });


            $.extend($.fn.dataTable.defaults, {
                'dom': 'Blfrtip',
                'processing': true,
                'serverSide': true,
                'ajax': '/burger/list',
                language: {
                    url: '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json'
                },
                'columns': arr

            });


            $('#burger_list').DataTable({

            });
        });
    </script>


{% endblock %}

templates/burger/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'un burger{% endblock %}

{% block body %}
    <div class="col-12">

        <h3>
            Création d'un burger
            <a href="{{ path('burger_index') }}" class="btn btn-primary float-right mt-2"><i class="fa fa-step-backward"></i>Revenir à la liste</a>
        </h3>

        {{ include('burger/_form.html.twig') }}
    </div>
{% endblock %}

templates/burger/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails d'un burger{% endblock %}

{% block body %}
    <div class="col-12">
        <h3>
            Détails d'un burger
            <a href="{{ path('burger_index') }}" class="btn btn-primary float-right mt-2"><i class="fa fa-step-backward"></i>Revenir à la liste</a>
        </h3>

        <table class="table">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ burger.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ burger.name }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ burger.description }}</td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>{{ burger.price }}</td>
                </tr>
                <tr>
                    <th>Supp_double</th>
                    <td>{{ burger.suppDouble }}</td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('burger_edit', {'id': burger.id}) }}" class="btn btn-primary"><i class="fa fa-pen"></i> Modifier</a>

        <br/><br/>

        {{ include('burger/_delete_form.html.twig') }}
    </div>
{% endblock %}